dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
# Run Ansible linter
- sudo pip install -r ansible/requirements.txt
- sudo pip install ansible-lint
- for playbook in ansible/playbooks/*.yml; do ansible-lint $playbook; if [[ $? != 0 ]]; then exit 127; fi;  done
# packer validate
- wget --directory-prefix=/tmp/ https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_linux_amd64.zip
- sudo unzip /tmp/packer_1.2.2_linux_amd64.zip -d /usr/sbin
- for template in packer/*.json; do packer validate -var-file=packer/variables.json.example $template; if [[ $? != 0 ]]; then exit 127; fi; done
# terraform validate &  linting
- wget --directory-prefix=/tmp/ https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
- wget --directory-prefix=/tmp/ https://github.com/wata727/tflint/releases/download/v0.5.4/tflint_linux_amd64.zip
- sudo unzip /tmp/terraform_0.11.7_linux_amd64.zip -d /usr/sbin
- sudo unzip /tmp/tflint_linux_amd64.zip -d /usr/sbin
- touch ~/.ssh/appuser.pub
- touch ~/.ssh/appuser
- cd terraform/stage && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example && tflint --var-file=terraform.tfvars.example
- cd ../prod && terraform init -backend=false && terraform validate -var-file=terraform.tfvars.example && tflint --var-file=terraform.tfvars.example


notifications:
  slack:
    secure: eSBsrM1re0SxOxUaqSe7hubObp8fMeVwvuGcFpuBjqu/CORNusz2MxZmVaZ4kTBiHBLZgxvgIKPrtgHQsQnL7pQbwn2Mmr/glWCDlOmFmXFcgoINKHVWcK7kDBYp/7jLkxr/z7511nyiGt1CXo8x2i8KcpjbU8u63BUcuBupPxcB773JvcqkYO4sOOEUxSwMdPej9A4iMouTiHO03yZ+ozMFltQGjnr8t33YGbBX+YhG3YquM2Iab3YLMpuzA0mbq65RPGq1e10zTlXL3e+V8vRrPsp+8uPrGMXn6gVu0nJC5ZpXJSNEGkUQjSX51kuISVkxB0WhzM5U/2NdllcINL3+U1dAqIo/RYeQN1VEXHaxVt6Mel4r/Q4k871b+Uy6lydsq0bftR4Hedyus7iuWdSylYgoJ+WL0OuUwa7iTKqBmwLGSb/Ge/zVXs067933hKDsjDvFIR5+OfYm1CC5XWOcczgpnbpxivF/Oas9YhUd4d+LrZka1ZsL++iw8K5/XKXiENDMS1AvxNZk9P3nRAQeCrUjaZAhOL596wvRAKJ9Yiie/rFGyRRauo0JWrXoj8al0DhaultIfJVUwfFF8nLQo0jFdR9+JuNz6A5sKT5nnkAxo4baIw3nbTM4jR8vU1uQCejo0AdnAydHSo1xOuZHu1sfbIouBahQM5LF2MU=
