---
- name: Configure application host
  hosts: app
  become: true
  vars:
    db_host: 10.132.0.2
  tasks:

    - name: Add Puma unit file
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config file with DB connection parameters
      template:
        src: templates/db_config.j2
        dest: /home/ivtcro/db_config
        owner: ivtcro
        group: ivtcro

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
