---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:

    - name: Get repository key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927

    - name: Add repository
      apt_repository:
          repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse

    - name: Install MongoDB
      update_cache: yes
      apt:
          name: mongodb-org

    - name: Enable&Run MongoDB service
      systemd:
        name: mongod
        enabled: yes
        state: started
